# this is a node build
language: node_js

# cache node modules
cache:
  directories:
    - "node_modules"

# install dependencies
install:
  - npm install --silent

# the jobs for building and deplyoing docs and demo
jobs:
  include:
    - stage: build core, docs and demo
      script: npm run build:core
      deploy:
        provider: npm
        skip_cleanup: true
        local_dir: dist/core
        email: $NPM_EMAIL
        api_key: $NPM_KEY
        on:
          tags: true
          repo: ngx-material-keyboard/core
          branch: master
    - # stage name not required, will continue to use `build core, docs and demo`
      script: npm run build:docs
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: dist/docs
        github_token: $GITHUB_TOKEN
        target_branch: gh-pages
        on:
          repo: ngx-material-keyboard/core
          branch: master
    - # stage name not required, will continue to use `build core, docs and demo`
      script: npm run build:demo
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: dist/demo
        github_token: $GITHUB_TOKEN
        repo: ngx-material-keyboard/demo
        target_branch: master
        on:
          repo: ngx-material-keyboard/core
          branch: master